CREATE TABLE notification (
  id BIGSERIAL PRIMARY KEY,
  status VARCHAR NOT NULL,
  yard_contact BIGINT NOT NULL REFERENCES person(id),
  site_foreman BIGINT NOT NULL REFERENCES person(id),
  additional_information VARCHAR NOT NULL,
  work_week_week_number INT NOT NULL,
  work_week_monday_start_time_hour INT,
  work_week_monday_start_time_minute INT,
  work_week_monday_end_time_hour INT,
  work_week_monday_end_time_minute INT,
  work_week_tuesday_start_time_hour INT,
  work_week_tuesday_start_time_minute INT,
  work_week_tuesday_end_time_hour INT,
  work_week_tuesday_end_time_minute INT,
  work_week_wednesday_start_time_hour INT,
  work_week_wednesday_start_time_minute INT,
  work_week_wednesday_end_time_hour INT,
  work_week_wednesday_end_time_minute INT,
  work_week_thursday_start_time_hour INT,
  work_week_thursday_start_time_minute INT,
  work_week_thursday_end_time_hour INT,
  work_week_thursday_end_time_minute INT,
  work_week_friday_start_time_hour INT,
  work_week_friday_start_time_minute INT,
  work_week_friday_end_time_hour INT,
  work_week_friday_end_time_minute INT,
  work_week_saturday_start_time_hour INT,
  work_week_saturday_start_time_minute INT,
  work_week_saturday_end_time_hour INT,
  work_week_saturday_end_time_minute INT,
  work_week_sunday_start_time_hour INT,
  work_week_sunday_start_time_minute INT,
  work_week_sunday_end_time_hour INT,
  work_week_sunday_end_time_minute INT
);
