INSERT INTO person (
  id,
  first_name,
  last_name,
  company,
  contact_information_email,
  contact_information_phone_number,
  confirmed,
  token,
  password,
  key_code
) VALUES (
  1 /* Ville Peurala */,
  'Ville',
  'Peurala',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
), (
  2 /* Tero Packalen */,
  'Tero',
  'Packalen',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
), (
  3 /* Ville Peurala with contact information */,
  'Ville',
  'Peurala',
  SELECT id FROM company WHERE id = 3 /* STX Group */,
  'ville.peurala@mail.com',
  '050 - 352 7878',
  NULL,
  NULL,
  NULL,
  NULL
), (
  4 /* Tero Packalen with contact information */,
  'Tero',
  'Packalen',
  SELECT id FROM company WHERE id = 2 /* Maersk */,
  'tero.packalen@yard.com',
  '040 - 568 3313',
  NULL,
  NULL,
  NULL,
  NULL
), (
  5 /* ville.peurala@gmail.com */,
  'Ville',
  'Peurala',
  SELECT id FROM company WHERE id = 3 /* STX Group */,
  'ville.peurala@mail.com',
  '050 - 352 7878',
  true,
  '76696c6c652e70657572616c614077756e646572646f672e6670',
  NULL,
  NULL
), (
  6 /* tero.packalen@yard.com */,
  'Tero',
  'Packalen',
  SELECT id FROM company WHERE id = 2 /* Maersk */,
  'tero.packalen@yard.com',
  '040 - 568 3313',
  true,
  '76696c6c652e70657572616c614077756e646572646f672e6671',
  NULL,
  NULL
), (
  7 /* Jurij Andrejev */,
  'Jurij',
  'Andrejev',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '4060'
), (
  8 /* Genadij Bogira */,
  'Genadij',
  'Bogira',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2332'
);
