DROP TABLE IF EXISTS log_entry;
DROP TABLE IF EXISTS work_entry;
DROP TABLE IF EXISTS notification;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS building;
DROP TABLE IF EXISTS ship;
DROP TABLE IF EXISTS ship_area;
DROP TABLE IF EXISTS company;